/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import controller.Controller;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Nastavnik;
import model.Zvanje;

/**
 *
 * @author necam
 */
public class DetaljiNastavnikForma extends javax.swing.JDialog {

    private Nastavnik odabraniNastavnik = Controller.getOdabraniNastavnik();
    PrikazNastavnikaForma roditelj;

    /**
     * Creates new form DetaljiNastavnikForma
     */
    public DetaljiNastavnikForma(javax.swing.JFrame parent) {
        initComponents();
        setLocationRelativeTo(null);
        this.roditelj = (PrikazNastavnikaForma) parent;
        popuniComboBox();
        txtIme.setText(odabraniNastavnik.getIme());
        txtIme.setEnabled(false);
        txtPrezime.setText(odabraniNastavnik.getPrezime());
        txtPrezime.setEnabled(false);
        cmbZvanje.setSelectedItem(odabraniNastavnik.getZvanje());
        cmbZvanje.setEnabled(false);
        btnSacuvaj.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbZvanje = new javax.swing.JComboBox<>();
        btnObrisi = new javax.swing.JButton();
        btnOmoguci = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ime:");

        jLabel2.setText("prezime:");

        jLabel3.setText("zvanje:");

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnOmoguci.setText("Omoguci izmenu");
        btnOmoguci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOmoguciActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIme)
                            .addComponent(txtPrezime)
                            .addComponent(cmbZvanje, 0, 251, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSacuvaj)
                        .addGap(18, 18, 18)
                        .addComponent(btnOmoguci)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisi)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbZvanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisi)
                    .addComponent(btnOmoguci)
                    .addComponent(btnSacuvaj))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
       int potvrda = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete?", "Potvrda", JOptionPane.YES_NO_OPTION);
       if(potvrda == JOptionPane.YES_OPTION) {
            try {
                boolean uspesno = Controller.getInstance().obrisiNastavnika(odabraniNastavnik.getId());
                if (uspesno) {
                    JOptionPane.showMessageDialog(this, "Uspesno obrisano!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Greska pri brisanju!", "Greska", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(DetaljiNastavnikForma.class.getName()).log(Level.SEVERE, null, ex);
            }
            roditelj.osveziTabelu();
            this.dispose();
       }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnOmoguciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOmoguciActionPerformed
        txtIme.setEnabled(true);
        txtPrezime.setEnabled(true);
        cmbZvanje.setEnabled(true);
        btnSacuvaj.setVisible(true);
    }//GEN-LAST:event_btnOmoguciActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            String ime = txtIme.getText();
            String prezime = txtPrezime.getText();
            Zvanje zvanje = (Zvanje) cmbZvanje.getSelectedItem();
            int id = odabraniNastavnik.getId();
            if(ime == null  || ime.isEmpty()  || prezime == null || prezime.isEmpty() || zvanje == null) {
                JOptionPane.showMessageDialog(this, "Sva polju su obavezna!", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if(ime.length() > 100 || prezime.length() > 100) {
                JOptionPane.showMessageDialog(this, "Predugacko ime ili prezime", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            //[A-Za-z]+
            if(!ime.matches("[A-Za-z]+") || !prezime.matches("[A-Za-z]+")) {
                JOptionPane.showMessageDialog(this, "Nisu svi karakteri slova u imenu ili prezimenu!", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            boolean uspesno = Controller.getInstance().azurirajNastavnika(id, ime, prezime, zvanje);
            if(uspesno) {
                JOptionPane.showMessageDialog(this, "Uspesno azurirano");
            } else {
                JOptionPane.showMessageDialog(this, "Greska pri azuriranju");
            }
        } catch (SQLException ex) {
            Logger.getLogger(DetaljiNastavnikForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        roditelj.osveziTabelu();
        this.dispose();
            
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnOmoguci;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<Zvanje> cmbZvanje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
    private void popuniComboBox() {
        List<Zvanje> svaZvanja = Controller.getInstance().vratiZvanja();
        cmbZvanje.addItem(null);
        for (Zvanje zvanje : svaZvanja) {
            cmbZvanje.addItem(zvanje);
        }
    }

}
