/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import controller.Controller;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import model.Nastavnik;
import model.Zvanje;

/**
 *
 * @author necam
 */
public class PrikazNastavnikaForma2 extends javax.swing.JFrame {

    /**
     * Creates new form PrikazNastavnikaForma
     */
    public PrikazNastavnikaForma2() {
        initComponents();
        setLocationRelativeTo(null);
        List<Nastavnik> lista = Controller.getInstance().vratiNastavnike();
        ModelTabeleNastavnik mtn = new ModelTabeleNastavnik(lista);
        tblNastavnik.setModel(mtn);
        
        List<Zvanje> listaZvanja = Controller.getInstance().vratiZvanja();
        JComboBox<Zvanje> cmbZvanje = new JComboBox<>();
        for (Zvanje zvanje : listaZvanja) {
            cmbZvanje.addItem(zvanje);
        }
        TableColumn kolonaZvanje = tblNastavnik.getColumnModel().getColumn(2);
        kolonaZvanje.setCellEditor(new DefaultCellEditor(cmbZvanje));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNastavnik = new javax.swing.JTable();
        btnDodajRed = new javax.swing.JButton();
        btnObrisiRed = new javax.swing.JButton();
        btnSinhronizuj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblNastavnik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNastavnik);

        btnDodajRed.setText("Dodaj red");
        btnDodajRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajRedActionPerformed(evt);
            }
        });

        btnObrisiRed.setText("Obrisi red");
        btnObrisiRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiRedActionPerformed(evt);
            }
        });

        btnSinhronizuj.setText("Sinhronizuj tabelu sa BP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnDodajRed)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisiRed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSinhronizuj, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajRed)
                    .addComponent(btnObrisiRed)
                    .addComponent(btnSinhronizuj))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObrisiRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiRedActionPerformed
        int selektovaniRed = tblNastavnik.getSelectedRow();
        if(selektovaniRed == -1) {
            JOptionPane.showMessageDialog(this, "Niste izabrali nijednog nastavnika!", "Greska", JOptionPane.ERROR_MESSAGE);
        } else {
            ModelTabeleNastavnik mtn = (ModelTabeleNastavnik) tblNastavnik.getModel();
            mtn.obrisiNastavnika(selektovaniRed);
        }
    }//GEN-LAST:event_btnObrisiRedActionPerformed

    private void btnDodajRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajRedActionPerformed
       ModelTabeleNastavnik mtn = (ModelTabeleNastavnik) tblNastavnik.getModel();
       List<Nastavnik> lista = mtn.getLista();
        for (Nastavnik nastavnik : lista) {
            if(nastavnik.getIme() == null || nastavnik.getIme().isEmpty()  || nastavnik.getPrezime() == null || nastavnik.getPrezime().isEmpty() || nastavnik.getZvanje() == null) {
                JOptionPane.showMessageDialog(this, "Nisu validni podaci iz prethodnih redova!");
                return;
            }
        }
        
        
        
        Nastavnik n = new Nastavnik();
        
        mtn.dodajNastavnika(n);
    }//GEN-LAST:event_btnDodajRedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrikazNastavnikaForma2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrikazNastavnikaForma2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrikazNastavnikaForma2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrikazNastavnikaForma2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrikazNastavnikaForma2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajRed;
    private javax.swing.JButton btnObrisiRed;
    private javax.swing.JButton btnSinhronizuj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNastavnik;
    // End of variables declaration//GEN-END:variables

    void osveziTabelu() {
        List<Nastavnik> lista = Controller.getInstance().vratiNastavnike();
        ModelTabeleNastavnik mtn = new ModelTabeleNastavnik(lista);
        tblNastavnik.setModel(mtn);
    }
}
